remove unnecessary use  getOptimizationPhaseIsComplete and LateSequen…
eclipse/openj9 pull request #10536
Opened 2020-09-08 17:06 UTC by rudy2steiner

Remove LateSequentialConstantStoreSimplification phse and unnecessary code invoke

fix issue #10181 and #10180

2020-09-08 18:36 UTC, 0xdaryl commented
Thanks for the contribution!

* Please be sure you've signed the ECA per the project's legal requirements -> https://github.com/eclipse/openj9/blob/master/CONTRIBUTING.md#legal-considerations

* Please be sure the forward copyright date in the file header comment is updated to 2020 in all files you've changed

* As you are addressing two separate issues in this PR, please split the changes for each into their own commit (you can still use one PR for both issues, but different commits).

2020-09-10 03:40 UTC, rudy2steiner commented
I met a exception when sign eca
```
Error, An error has occured and your Eclipse Contributor Agreement was not submitted. (ECA-04)
```

2020-09-10 13:46 UTC, 0xdaryl commented
There have been a very small number of reports in the past about problems signing the ECA.  To my knowledge all of these went away with the short passage of time.  Please try again later.

Unfortunately, signing the ECA is an Eclipse Foundation process (not controlled or managed by OpenJ9) so if the problems persist for you the next course of action is to inquire with the Eclipse Foundation for assistance (e.g., through the Eclipse Community Forum).

2020-09-11 02:00 UTC, rudy2steiner commented
Ok, i will try to contact with eclipse email or Forum

2020-11-22 06:53 UTC, rudy2steiner commented
@0xdaryl would you mind help me review this work!

2021-04-12 18:27 UTC, 0xdaryl requested changes
My apologies--this PR seems to have slipped through the cracks.  Code changes generally look good.  A couple of minor points:

* Please shorten the PR title so that it is not truncated
* Please capitalize the first word in each commit title per the Contributor Guidelines
* Update all forward copyrights to 2021

2021-04-12 18:27 UTC, 0xdaryl commented on runtime/compiler/codegen/J9CodeGenPhaseFunctionTable.hpp
> +   TR::CodeGenPhase::performIdentifyUnneededByteConvsPhase,                                  //IdentifyUnneededByteConvsPhase
Missing EOL here.

2021-04-18 02:50 UTC, rudy2steiner commented
@0xdaryl  Thanks for you feedbacks, updated!

2021-04-19 13:34 UTC, 0xdaryl commented
Jenkins test sanity all jdk8,jdk11

2021-04-19 18:27 UTC, 0xdaryl commented
Jenkins test sanity osx jdk8

2021-04-20 00:08 UTC, 0xdaryl approved these changes

2021-04-20 00:10 UTC, 0xdaryl commented
Jenkins test sanity osx jdk8

2021-04-20 10:29 UTC, merged