WIP: File4 buffer
eclipse/openj9 pull request #10879
Opened 2020-10-14 02:44 UTC by gza060625

2020-10-14 15:11 UTC, RSalman requested changes

2020-10-14 15:11 UTC, RSalman commented on runtime/gc_verbose_java/VerboseHandlerJava.cpp
>  MM_VerboseHandlerJava::writeVmArgs(MM_VerboseManager *manager, MM_EnvironmentBase* env, J9JavaVM *vm)
Is this function still needed?

2020-10-15 21:51 UTC, RSalman requested changes

2020-10-15 21:51 UTC, RSalman commented on runtime/gc_verbose_handler_realtime/VerboseHandlerOutputRealtime.cpp
>  	handleInitializedRegion(hook, eventNum, eventData);
Please look into if this needs to be changed to use buffer. I think it does like `outputInitializedInnerStanza` is

2020-10-20 00:07 UTC, RSalman requested changes

2020-10-20 00:07 UTC, RSalman commented on runtime/gc_verbose_java/VerboseHandlerJava.hpp
> +	static void writeVmArgs(MM_EnvironmentBase* env, MM_VerboseBuffer* buffer,J9JavaVM* vm);
Minor formatting: space before `J9JavaVM..`

2020-10-28 21:32 UTC, RSalman requested changes
You can args from init trigger, `j9gc_get_gcmodestring(vm)` and anything following it
https://github.com/eclipse/openj9/blob/bb626b213f343b38bb3a610b5cdf86a50f8f0174/runtime/gc_modron_startup/mminit.cpp#L3105-L3132

2020-10-28 21:32 UTC, RSalman commented on runtime/gc_verbose_handler_realtime/VerboseHandlerOutputRealtime.cpp
> +	MM_GCExtensionsBase *extension = env->getExtensions();
Minor nit pick: `extension` to `extensions`

2020-12-01 18:26 UTC, amicic commented
Jenkins test sanity win jdk11

2020-12-01 18:26 UTC, amicic commented
Jenkins compile all jdk8

2020-12-01 22:08 UTC, RSalman approved these changes

2020-12-04 16:54 UTC, merged