enable cmdLineTest_locales on openj9
eclipse/openj9 pull request #11050
Opened 2020-10-29 19:59 UTC by OscarQQ

related: backlog issue 384
related: https://github.com/eclipse/openj9/pull/10610

2020-10-29 20:02 UTC, OscarQQ commented
vmfarm build id 458416

2020-10-29 20:04 UTC, OscarQQ commented
| Build       | Platform           | Java Version  | JDK Impl |
|:-------------:|:-------------:|:-----:|:-----------:|
|[Grinder/4364](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4364)|ppc64le_linux,ppc64le_linux_xl,x86-64_mac,s390x_linux,s390x_linux_xl,x86-64_linux,ppc64_aix,x86-64_linux_xl|8,11|OpenJ9|

2020-10-29 20:04 UTC, OscarQQ commented
@llxia could you review this? thanks

2020-10-29 20:19 UTC, pshipton commented
This is not my preference for how to fix the test. It's a loss in testing for IBM Java which does support some (all?) these charsets. The better solution is to modify the test to allow UnsupportedCharsetException without having it cause the test to fail.

2020-10-29 20:27 UTC, llxia commented
Yes, I agree. I would suggest making two lists - one for ibm and one for non-ibm for now. And we can work on programmatically detecting supported charsets as an enhancement in the future PR.

2020-10-29 20:46 UTC, pshipton commented
I don't think it's hard to fix. Something like the following.
- redirect the output to a file
- record the return code into a variable
- adjust the result based on finding UnsupportedCharsetException in the output
- check the result to determine pass/fail

```
    $1 "${@:2}" &> output ; result = "$?"
    grep UnsupportedCharsetException output 
    if [ "$?" = 0 ]; then
      result = 0
    fi
    if [ $result != 0 ]; then
      echo "bad return code"
    fi
```

2020-11-02 04:45 UTC, OscarQQ commented
| Build       | Platform           | Java Version  | JDK Impl |
|:-------------:|:-------------:|:-----:|:-----------:|
|Grinder/11714|ppc64le_linux,ppc64le_linux_xl,x86-64_mac,s390x_linux,s390x_linux_xl,x86-64_linux,ppc64_aix,x86-64_linux_xl|8,11|OpenJ9|

2020-11-02 04:47 UTC, OscarQQ commented
@llxia could you review this? thanks :)

2020-11-02 19:23 UTC, pshipton approved these changes

2020-11-02 19:46 UTC, keithc-ca requested changes

2020-11-02 19:46 UTC, keithc-ca commented on test/functional/cmdLineTests/locales/run_all_locales.sh
> +    if [ "$?" = 0 ]; then
These two lines should be combined and grep output suppressed:
```
if grep -q UnsupportedCharsetException <<< "$output" ; then
```
(note also that `UnsupportedCharsetException` need not be quoted and that `$output` should be quoted)

2020-11-03 14:44 UTC, keithc-ca approved these changes

2020-11-03 16:00 UTC, llxia commented
Please update the above Ginder links and run a vmfarm personal build. Thanks

2020-11-04 19:26 UTC, OscarQQ commented
| Build       | Platform           | Java Version  | JDK Impl |
|:-------------:|:-------------:|:-----:|:-----------:|
|Grinder/11857|ppc64le_linux,ppc64le_linux_xl,s390x_linux,s390x_linux_xl,x86-64_linux,ppc64_aix,x86-64_linux_xl|8,11|OpenJ9|
|[Grinder/4538](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4538)|x86-64_mac|8,11|OpenJ9|

vmfarm build_id=458927

2020-11-05 22:05 UTC, llxia commented
jenkins test extended all jdk8,jdk11

2020-11-06 14:37 UTC, llxia commented
jenkins test extended win jdk8

2020-11-06 16:15 UTC, llxia commented
PR builds failed in [Build_JDK8_x86-64_windows](https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_Personal/946/console). This failure is not related to this PR. Since the test passed on all other platforms and the test does not run on windows, I am going to merge this PR.

2020-11-06 16:15 UTC, llxia approved these changes
LGTM

2020-11-06 16:16 UTC, merged