Add a stub for NativeMethodHandle in JDK16
eclipse/openj9 pull request #11267
Opened 2020-11-24 21:09 UTC by babsingh

fixes: https://github.com/eclipse/openj9/issues/11255

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>

2020-11-24 21:18 UTC, babsingh commented
I tried to turn-on the `opt_panama` and `Panama` (JCL) flags in order to enable the OpenJ9 `NativeMethodHandle` support. But, I ended up facing many issues:
1. `jdk.internal.nicl` and `java.nicl` packages no longer exist in JDK16. Finding their new equivalent representation will take some time. 
2. `MethodHandles` class no longer has the `findNative*` methods.
3. `Library` class is no longer available; potentially renamed to `NativeLibrary` and relocated.
4. `gcc` error: `Jit.hpp` in `JavaMethodCallbackGen.cpp` cannot be found.
5. ... the list goes on

The above conflicts cannot be resolved quickly. So, I have added a minimal stub for the `NativeMethodHandle` class, which should allow us to quickly enable JDK16 builds.

2020-11-24 21:20 UTC, babsingh commented
Suggested PR builds:
```
Jenkins test sanity xlinux jdk11
Jenkins test sanity xlinux jdknext
Jenkins test zlinux jdknext depends ibmruntimes/openj9-openjdk-jdk#openj9-staging
```
All builds should pass.

2020-11-24 21:22 UTC, babsingh commented
fyi @tajila @JasonFengJ9 @pshipton @gacholio @keithc-ca

2020-11-24 21:27 UTC, tajila commented
Jenkins test sanity xlinux jdk11

2020-11-24 21:27 UTC, tajila commented
Jenkins test sanity plinux jdknext

2020-11-24 21:27 UTC, tajila commented
Jenkins test sanity zlinux jdknext depends ibmruntimes/openj9-openjdk-jdk#openj9-staging

2020-11-24 22:10 UTC, keithc-ca requested changes

2020-11-24 22:10 UTC, keithc-ca commented on jcl/src/java.base/share/classes/java/lang/invoke/NativeMethodHandle.java
> +		return null;
All uses of `OpenJDKCompileStubThrowError()` should be in a `throw` statement:
```
  throw OpenJDKCompileStub.OpenJDKCompileStubThrowError();
```

2020-11-24 22:10 UTC, keithc-ca commented on jcl/src/java.base/share/classes/java/lang/invoke/NativeMethodHandle.java
> +/*[ELSE]*/
This should repeat the condition:
```
/*[ELSE] Panama */
```

2020-11-24 22:10 UTC, keithc-ca commented on jcl/src/java.base/share/classes/java/lang/invoke/NativeMethodHandle.java
> +/*[INCLUDE-IF Panama|(JAVA_SPEC_VERSION >= 16)]*/
Please use spaces around binary operators, just like you would in C code:
```
/*[INCLUDE-IF Panama | (JAVA_SPEC_VERSION >= 16)]*/
```

2020-11-24 22:58 UTC, keithc-ca commented on jcl/src/java.base/share/classes/java/lang/invoke/NativeMethodHandle.java
> +		return null;
This won't compile: the `return` here (and in `addRelatedMHs()`) is unreachable.

2020-11-24 23:10 UTC, babsingh commented
All the recent feedback has been addressed. Unfortunately, `jdknext openj9` build will be unsuccessful since `NativeEntryPoint` only exists in `jdknext openj9-staging` at this point.

2020-11-25 13:01 UTC, keithc-ca commented
Jenkins test sanity xlinux jdk11

2020-11-25 13:01 UTC, keithc-ca commented
Jenkins test sanity zlinux jdknext depends ibmruntimes/openj9-openjdk-jdk#openj9-staging

2020-11-25 14:11 UTC, keithc-ca approved these changes

2020-11-25 16:17 UTC, merged