Add ability to delete tso datasets for zOS guests
eclipse/openj9 pull request #11412
Opened 2020-12-08 20:40 UTC by jdekonin

* [skip ci]

Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

2020-12-08 20:42 UTC, jdekonin commented
@vsebe @AdamBrousseau @pshipton for review

2020-12-08 20:53 UTC, AdamBrousseau requested changes
Indenting uses tabs instead of spaces
![image](https://user-images.githubusercontent.com/6430052/101540047-6e51b880-396d-11eb-9448-297aaebce826.png)

2020-12-08 21:10 UTC, jdekonin commented
> Indenting uses tabs instead of spaces

Done.

2020-12-08 21:26 UTC, pshipton commented on buildenv/jenkins/jobs/infrastructure/Cleanup-Nodes.groovy
> +                                        listcat = sh(script: "tso listcat | grep '${env.USER}' | cut -d. -f 2-", returnStdout: true).trim()
Are you sure this works? It seems like it should but when I try `tso listcat | grep JENKINS` manually, it doesn't find anything although there is a dataset there.

2020-12-08 21:32 UTC, pshipton commented on buildenv/jenkins/jobs/infrastructure/Cleanup-Nodes.groovy
> +                                        listcat = sh(script: "tso listcat | grep '${env.USER}' | cut -d. -f 2-", returnStdout: true).trim()
Trying something else `tso listcat | tee out` it outputs garbage, making me thing there is a ascii/ebcdic issue.

`tso listcat > out && grep JENKINS out` works.

2020-12-08 21:32 UTC, pshipton commented on buildenv/jenkins/jobs/infrastructure/Cleanup-Nodes.groovy
> +                                        listcat = sh(script: "tso listcat | grep '${env.USER}' | cut -d. -f 2-", returnStdout: true).trim()
I was using fyrec50g

2020-12-08 21:34 UTC, pshipton commented on buildenv/jenkins/jobs/infrastructure/Cleanup-Nodes.groovy
> +                                        listcat = sh(script: "tso listcat | grep '${env.USER}' | cut -d. -f 2-", returnStdout: true).trim()
Actually `sh -c "tso listcat | grep JENKINS"` works, so I guess this will too.

2020-12-09 01:52 UTC, AdamBrousseau approved these changes
lftm assuming the commands work as expected.

2020-12-09 02:09 UTC, pshipton approved these changes

2020-12-09 02:09 UTC, merged