WIP: Convert `concurrent-mark-end` to `gc-op` in GMP concurrent increment
eclipse/openj9 pull request #11578
Opened 2021-01-06 02:32 UTC by gza060625

https://github.com/eclipse/openj9/issues/11239
This is the OpenJ9 part to convert `concurrent-mark-end` to `gc-op` in GMP concurrent increment .

- Implement new API to get termination reason
	`MM_VerboseHandlerOutputVLHGC::getReasonForTermination`

2021-01-15 01:37 UTC, RSalman requested changes

2021-01-15 01:37 UTC, RSalman commented on runtime/gc_vlhgc/IncrementalGenerationalGC.cpp
> +	static_cast<MM_CycleStateVLHGC*>(env->_cycleState)->_vlhgcIncrementStats._markStats._endTime = omrtime_hires_clock();
Do we need to set the end time? Seems like TS is passed to the trigger, we can make use of that.

2021-01-15 01:43 UTC, RSalman requested changes

2021-01-15 01:43 UTC, RSalman commented on runtime/gc_vlhgc/IncrementalGenerationalGC.cpp
> -	Assert_MM_true(NULL == env->_cycleState);
Instead of removing it completely, we change this to assert `env->_cycleState == _persistentGlobalMarkPhaseState;`

2021-01-15 01:43 UTC, RSalman commented on runtime/gc_vlhgc/IncrementalGenerationalGC.cpp
> +	static_cast<MM_CycleStateVLHGC*>(env->_cycleState)->_vlhgcIncrementStats._markStats._startTime = omrtime_hires_clock();
For consistency,`omrtime_hires_clock` -> `j9time_hires_clock`

2021-01-15 01:43 UTC, RSalman commented on runtime/gc_verbose_handler_vlhgc/VerboseHandlerOutputVLHGC.hpp
> +	const char *getTerminationReason(J9HookInterface** hook, UDATA eventNum, void* eventData);
`getConcurrentTerminationReason` is a more suitable name

2021-01-15 23:54 UTC, RSalman approved these changes
Approving given the minor changes are made

2021-01-15 23:54 UTC, RSalman commented on runtime/gc_vlhgc/IncrementalGenerationalGC.cpp
> +	Assert_MM_true(NULL == env->_cycleState);
You can move this assert up with the assert on line 1923

2021-01-15 23:54 UTC, RSalman commented on runtime/gc_verbose_handler_vlhgc/VerboseHandlerOutputVLHGC.cpp
> +	if (stats->_terminationWasRequested) {
Please add new line before this

2021-01-15 23:54 UTC, RSalman commented on runtime/gc_verbose_handler_vlhgc/VerboseHandlerOutputVLHGC.cpp
> +MM_VerboseHandlerOutputVLHGC::getConcurrentTerminationReason(J9HookInterface** hook, UDATA eventNum, void* eventData)
Lets change this to take in stats and remove hook+event data, `MM_ConcurrentPhaseStatsBase stats`

see https://github.com/eclipse/omr/pull/5736#discussion_r558582223

2021-01-27 13:31 UTC, amicic approved these changes

2021-01-27 13:32 UTC, amicic commented
Jenkins test sanity win,aix jdk8

2021-01-27 21:40 UTC, amicic commented
Compile errors.... I guess you need to forward declare MM_ConcurrentPhaseStatsBase  in VerboseHandlerOutputVLHGC.hpp.

2021-01-28 16:50 UTC, amicic commented
Jenkins test sanity win,aix jdk8

2021-02-09 15:05 UTC, merged