[WIP] Tag classes generated for OpenJDK MethodHandles during resolution
eclipse/openj9 pull request #11715
Opened 2021-01-20 22:17 UTC by fengxue-IS

Tag the classes generated for OpenJDK MethodHandles so that JIT can identify them.
Classes are tagged with flag `J9ClassIsGeneratedForOJDKMethodHandle` during MHN.resolve()

Co-authored-by: Babneet Singh <sbabneet@ca.ibm.com>
Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>

2021-01-20 22:20 UTC, fengxue-IS commented
This change is on top of #10690, will need to cherry-pick/rebase once #10690 is merged
FYI @liqunl @babsingh

This is a new approach that should replace #11599

2021-01-20 22:51 UTC, babsingh commented
@liqunl does the JIT also require a helper to check if a J9Method's class is tagged?
**Example:** [bool VM_VMHelpers::methodFromOJDKMHGeneratedClass(J9Method *method)](https://github.com/eclipse/openj9/pull/11599/files)

2021-02-03 17:49 UTC, fengxue-IS commented
@gacholio can you please take a look

2021-02-03 17:56 UTC, gacholio commented
This seems like overkill - given the simplicity of the test, why not provide a macro/function to query the method (or method class)?

@liqunl

2021-02-03 18:00 UTC, babsingh requested changes
commit message has \`J9ClassIsGeneratedForOJDKMethodHandle\` and it exceeds the char limit per line.

2021-02-03 18:01 UTC, gacholio commented on runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
> +					if (J9_ARE_ANY_BITS_SET(methodClass->classFlags, J9ClassIsAnonymous) || (J9ROMCLASS_IS_HIDDEN(methodClass->romClass))) {
I always use ANY for single bit checks, though the compiler would hopefully optimize the ALL case.

2021-02-03 18:38 UTC, gacholio commented on runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
> +							methodClass->classFlags |= J9ClassIsGeneratedForOJDKMethodHandle;
This is not a thread-safe operation. If we continue with this approach, this would be better done during RAM class creation.

2021-02-03 20:36 UTC, liqunl commented
> This seems like overkill - given the simplicity of the test, why not provide a macro/function to query the method (or method class)?

The JIT can do some query of the method's bytecodes, but the concern is that there isn't one or two specific thing that can tell us whether the method is generated for MH. The changes are in MethodHandleNatives where we associates a j9method with a MemberName object, so this must be a method generated for MH (except for the leaf method).

If adding a class flag is really concerning, the JIT can still try to query the method, but the JIT has to tolerate some mistakes which shouldn't be very bad. We can go back to the tagging solution if there are problems the JIT can't handle. @gacholio

2021-02-03 20:44 UTC, gacholio commented
@liqunl I'm saying that we provide a query macro rather than consuming a flag bit, not that we don't do it at all.

2021-02-03 21:01 UTC, liqunl commented
@gacholio What kind of query are you proposing? Does it need a class flag bit?

2021-02-03 21:16 UTC, babsingh commented
> What kind of query are you proposing? Does it need a class flag bit?

guess: exactly what we are doing before setting the flag. instead of setting the flag, either true or false will be returned.

2021-02-03 21:18 UTC, fengxue-IS commented
@liqunl I think what Gac meant is that instead of using a class flag, we directly provide the check used for setting the flag as an API. 
Something similar to:
```
bool isLambdaFormGenerated(J9Method *method) {
    J9Class *methodClass = J9_CLASS_FROM_METHOD(method);
    J9Class *lambdaFormClass = J9VMJAVALANGINVOKELAMBDAFORM(vm);
    return (J9_ARE_ANY_BITS_SET(methodClass->classFlags, J9ClassIsAnonymous) || J9ROMCLASS_IS_HIDDEN(methodClass->romClass)) && (methodClass->hostClass == lambdaFormClass);
}
```
where JIT can pass in a `J9Method

2021-02-03 21:44 UTC, liqunl commented
@babsingh @fengxue-IS I think the JIT wants the VM to tell if a j9method is generated for LambdaForm, or more specifically, if a j9method has been stored in a MemberName object. Based on our previous discussion, the following check can't guarantee that, thus we decided to tag the class of the method when we store the j9method pointer to a MemberName object. So the following check is able to do what we want?

```
bool isLambdaFormGenerated(J9Method *method) {
    J9Class *methodClass = J9_CLASS_FROM_METHOD(method);
    J9Class *lambdaFormClass = J9VMJAVALANGINVOKELAMBDAFORM(vm);
    return (J9_ARE_ANY_BITS_SET(methodClass->classFlags, J9ClassIsAnonymous) || J9ROMCLASS_IS_HIDDEN(methodClass->romClass)) && (methodClass->hostClass == lambdaFormClass);
}
```

2021-02-03 22:00 UTC, gacholio commented
Yes, though you need to add a thread/vm to the args.

2021-02-03 22:29 UTC, babsingh commented
> Based on our previous discussion, the following check can't guarantee that, thus we decided to tag the class of the method when we store the j9method pointer to a MemberName object.

`LambdaForm` is a package protected class. AFAIK, `LambdaForm` as `hostClass` should only be used for generated `MH/VH` methods. Unless this claim is countered, the above check should also work from the JIT.

`MHN.resolve`/`RAM class creation` will perform the check a lot fewer times than the JIT. Assuming, the JIT has to perform this check for every `J9Method` it plans to optimize. This was the reason `MHN.resolve` was chosen for the check. Moving the check to the JIT will delay the check. Not sure ... it may be possible for the JIT to perform the check only under certain cases. @liqunl can you do a cost-benefit analysis and let us know if it is cheaper to do the check in the JIT?

2021-02-04 13:11 UTC, liqunl commented
>LambdaForm is a package protected class. AFAIK, LambdaForm as hostClass should only be used for generated MH/VH methods. Unless this claim is countered, the above check should also work from the JIT.

Ok, my impression was that this is not guaranteed as we don't have control of OpenJDK's code. But if this claim holds, we can use the check. The cost is cheap and is not a concern to the JIT as we do it at compile time.

2021-02-04 15:40 UTC, babsingh commented
> my impression was that this is not guaranteed as we don't have control of OpenJDK's code

This statement is also true. There is no spec requirement which enforces the usage of the `LambdaForm` class. If OJDK code ever changes, then it will be our responsibility to identity the change and appropriately update the filter to identify the generated OJDK MH/VH methods. E.g. JDK14-: the generated methods are in anon classes; JDK15+: the generated methods are in hidden classes. If something similar happens in the future, the filter will break.

2021-02-04 16:04 UTC, gacholio commented
For future-proofing, the query function is better than the bit test (it also allows the query to be on a per-method basis, even if the implementation continues to look only at the method class).

2021-02-04 17:09 UTC, liqunl commented
Ok. I think it's ok to use the query function instead of the bit.

2021-02-05 16:02 UTC, gacholio commented
Another note - this query is used at JIT compile time, so it must not run java code. You will need to ensure the lambdaform class is preloaded and resolved in the VM constant pool and use the `_OR_NULL` flavour of the macro which simply reads the value from the CP.

2021-02-08 17:43 UTC, gacholio commented
Have you ensured that the lambdaform class is preloaded (if there are any fieldrefs in the VM CP it will automatically be loaded)?

2021-02-08 19:06 UTC, fengxue-IS commented
> Have you ensured that the lambdaform class is preloaded (if there are any fieldrefs in the VM CP it will automatically be loaded)?

Yes, the vmentry field from LambdaForm is refed in the VM CP
`<fieldref class="java/lang/invoke/LambdaForm" name="vmentry" signature="Ljava/lang/invoke/MemberName;"`

2021-02-08 19:15 UTC, babsingh approved these changes

2021-02-08 19:38 UTC, gacholio approved these changes

2021-02-08 19:39 UTC, gacholio commented
jenkins compile win jdk8

2021-02-08 20:25 UTC, merged