Do not hold compilation monitor in outOfProcessCompilationEnd
eclipse/openj9 pull request #11844
Opened 2021-02-01 19:35 UTC by dmitry-ten

As described in #11831, we do not want to hold the compilation
queue monitor while sending the last message with a compiled method
back to the client. We do not actually need the monitor on the server in
`outOfProcessCompilationEnd` so the acquisition is delayed until
the end of that method.

2021-02-01 19:35 UTC, dmitry-ten commented
@mpirvu fyi.
I will also run the experiment with many clients connected to the same server and check if `compQueueMonitor` contestion is any better with this change.

2021-02-01 19:47 UTC, dmitry-ten commented
Just pushed a small fix for build breaking.

2021-02-01 19:49 UTC, mpirvu commented on runtime/compiler/control/JITServerCompilationThread.cpp
> +   compInfo->debugPrint(vmThread, "+AM-", entry);
I am favoring moving this code at the end of postCompilationTasks() to minimize the time we hold the compilation monitor but also to keep the lock acquisition at the same level (for non-jitserver we acquire the compilation monitor in postCompilationTasks, so we should do it i this method for jitserver as well)

2021-02-01 20:04 UTC, dmitry-ten commented
Updated.

2021-02-01 21:01 UTC, mpirvu commented
I wonder what happens if we have an exception during `postCompilationtasks()`. It is possible because we allocate memory and because we send the compilation result. Then we enter again that problematic catch block where we put a fatal assert that compiler object must be NULL.

2021-02-01 21:10 UTC, dmitry-ten commented
`ServerStream::finishCompilation` has a try/catch block inside, so it won't throw. 
If memory allocation exception is a concern, then the assert in the other PR can be just removed.

2021-02-02 00:13 UTC, mpirvu commented
Is this still happening:
```
   if (_compInfo.getPersistentInfo()->getRemoteCompilationMode() == JITServer::SERVER)
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../compiler/control/CompilationThread.cpp:7735:69: error: use of undeclared identifier 'JITServer'
   if (_compInfo.getPersistentInfo()->getRemoteCompilationMode() == JITServer::SERVER)
                                                                    ^
clang++-3.8 -std=c++0x -w -fsyntax-only -ferror-limit=0  -Xclang -load -Xclang /home/runner/work/openj9/openj9/runtime/omr/tools/compiler/OMRChecker/OMRChecker.so -Xclang -add-plugin -Xclang omr-checker  -DBITVECTOR_BIT_NUMBERING_MSB -DJ9_PROJECT_SPECIFIC -DTR_HOST_X86 -DTR_HOST_64BIT -DBITVECTOR_64BIT -DLINUX -DTR_TARGET_X86 -DTR_TARGET_64BIT -DSUPPORTS_THREAD_LOCAL -D_LONG_LONG -DJ9HAMMER -I'/home/runner/work/openj9/openj9/runtime/omr/include_core' -I'/home/runner/work/openj9/openj9/runtime/omr/thread' -I'/home/runner/work/openj9/openj9/runtime/omr/gc/include' -I'../compiler/x/amd64' -I'../compiler/x' -I'../compiler' -I'../omr/compiler/x/amd64' -I'../omr/compiler/x' -I'../omr/compiler' -I'../omr' -I'..' -I'/home/runner/work/openj9/openj9/runtime/codert_vm' -I'/home/runner/work/openj9/openj9/runtime/gc_include' -I'/home/runner/work/openj9/openj9/runtime/include' -I'/home/runner/work/openj9/openj9/runtime/gc_glue_java' -I'/home/runner/work/openj9/openj9/runtime/jit_vm' -I'/home/runner/work/openj9/openj9/runtime/nls' -I'/home/runner/work/openj9/openj9/runtime/oti' -I'/home/runner/work/openj9/openj9/runtime/util' -I'/home/runner/work/openj9/openj9/build/runtime' -I'/home/runner/work/openj9/openj9/build/runtime/omr' -I'/home/runner/work/openj9/openj9/build/runtime/nls' -I'/home/runner/work/openj9/openj9/build/runtime/include' -I'/home/runner/work/openj9/openj9/build/runtime/compiler' -o ../compiler/control/JitDump.cpp.linted -c ../compiler/control/JitDump.cpp
2 errors generated.
make: *** [../compiler/control/CompilationThread.cpp.linted] Error 1
linter.mk:160: recipe for target '../compiler/control/CompilationThread.cpp.linted' failed
make: *** Waiting for unfinished jobs....
Error: Process completed with exit code 2.
```

2021-02-02 00:17 UTC, mpirvu commented
Jenkins compile xlinux jdk11

2021-02-02 01:40 UTC, mpirvu requested changes

2021-02-02 01:40 UTC, mpirvu commented on runtime/compiler/control/CompilationThread.cpp
> +   if (_compInfo.getPersistentInfo()->getRemoteCompilationMode() == JITServer::SERVER)
We need the `#if defined(J9VM_OPT_JITSERVER)` here. This is why the linter job fails

2021-02-02 15:04 UTC, mpirvu approved these changes
LGTM

2021-02-02 15:13 UTC, mpirvu commented
jenkins test sanity plinuxjit,xlinuxjit,zlinuxjit jdk11

2021-02-02 19:19 UTC, merged