Add JavaLangAccess.join(prefix, suffix, delimiter, elements, size)
eclipse/openj9 pull request #12547
Opened 2021-04-23 21:24 UTC by JasonFengJ9

Invoke `String` package private method `join(prefix, suffix, delimiter,elements, size)`.

depends on https://github.com/eclipse/openj9/pull/12209

With this PR and https://github.com/eclipse/openj9/pull/12209, `java -version` output is:
```
openjdk version "17-internal" 2021-09-14
OpenJDK Runtime Environment (build 17-internal+0-adhoc.fengjcaibmcom.openj9-openjdk-jdk)
Eclipse OpenJ9 VM (build jdk17ristr-jlajoin-c2d8cf4dd9, JRE 17 Mac OS X amd64-64-Bit Compressed References 20210423_000000 (JIT enabled, AOT enabled)
OpenJ9   - c2d8cf4dd9
OMR      - 22a4853ac
JCL      - bcdde3be245 based on jdk-17+19)
```

fixes https://github.com/eclipse/openj9/issues/12545

Signed-off-by: Jason Feng <fengj@ca.ibm.com>

2021-04-24 16:54 UTC, pshipton commented
Pls create a stub that returns null so the code can continue to compile, and then we'll deliver this after #12209

2021-04-25 23:35 UTC, JasonFengJ9 commented
> Pls create a stub that returns null so the code can continue to compile

A stub method returning `null` is not sufficient, following NPE will occur:
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.String.length()" because "group" is null
	at jdk.jdeps/com.sun.tools.jdeps.ModuleDotGraph$DotGraphBuilder.lambda$build$4(ModuleDotGraph.java:370)
	at jdk.jdeps/com.sun.tools.jdeps.ModuleDotGraph$DotGraphBuilder$$Lambda$63/0x00000000cc0ba760.test(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at jdk.jdeps/com.sun.tools.jdeps.ModuleDotGraph$DotGraphBuilder.build(ModuleDotGraph.java:371)
	at jdk.jdeps/com.sun.tools.jdeps.ModuleDotGraph.genDotFile(ModuleDotGraph.java:137)
	at jdk.jdeps/com.sun.tools.jdeps.ModuleDotGraph.genDotFiles(ModuleDotGraph.java:100)
	at build.tools.jigsaw.GenGraphs.genDotFiles(GenGraphs.java:246)
	at build.tools.jigsaw.GenGraphs.main(GenGraphs.java:112)
```

2021-04-27 18:04 UTC, pshipton commented
jenkins compile zlinux jdknext

2021-04-27 18:19 UTC, keithc-ca commented on jcl/src/java.base/share/classes/java/lang/Access.java
> +
No trailing whitespace, please.

2021-04-27 18:24 UTC, JasonFengJ9 commented on jcl/src/java.base/share/classes/java/lang/Access.java
> +
Removed.

2021-04-27 18:25 UTC, JasonFengJ9 commented
The pull request build failure is an infra issue.
```
Setting status of 62c6ff3d6cf7068b38ecdcb7eb7d0a17744df2f6 to FAILURE with url https://ci.eclipse.org/openj9/job/PullRequest-OpenJ9/5923/ and message: ' '
Using context: Pull Request - OpenJ9
java.io.IOException: Tried to load head FlowNodes for execution Owner[PullRequest-OpenJ9/5923:PullRequest-OpenJ9 #5923] but FlowNode was not found in storage for head id:FlowNodeId 1:96
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.initializeStorage(CpsFlowExecution.java:689)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.onLoad(CpsFlowExecution.java:726)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.getExecution(WorkflowRun.java:691)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.onLoad(WorkflowRun.java:550)
```

2021-04-27 18:48 UTC, keithc-ca commented
Jenkins compile zlinux jdknext

2021-04-27 19:29 UTC, keithc-ca commented
Jenkins compile zlinux jdknext depends ibmruntimes/openj9-openjdk-jdk#openj9-staging

2021-04-27 20:29 UTC, pshipton approved these changes

2021-04-27 20:32 UTC, pshipton commented
Hmm, delivering this will break the openj9-openjdk-jdk openj9 branch. I'm thinking it should be implemented via reflection for now so that both the openj9 and openj9-staging branches can work.

2021-04-27 20:33 UTC, pshipton requested changes
Hmm, delivering this will break the openj9-openjdk-jdk openj9 branch. I'm thinking it should be implemented via reflection for now so that both the openj9 and openj9-staging branches can work.

2021-04-27 20:36 UTC, keithc-ca commented
Another hack we might employ is to use the `OPENJDK_METHODHANDLES` flag which is not normally enabled in the openj9 branch.

2021-04-27 20:40 UTC, pshipton commented
> Another hack we might employ is to use the OPENJDK_METHODHANDLES flag which is not normally enabled in the openj9 branch

Agreed, this is better.

2021-04-27 21:31 UTC, JasonFengJ9 commented
Decorated the code in question with `OPENJDK_METHODHANDLES` to workaround the issue that latest `String` update hasn't been promoted into `openj9` branch.

2021-04-27 21:36 UTC, keithc-ca commented
Jenkins compile zlinux jdknext

2021-04-27 21:37 UTC, keithc-ca commented
I don't think we need to repeat the build using the openj9-staging branch.

2021-04-28 01:10 UTC, pshipton approved these changes

2021-04-28 01:10 UTC, merged