Add DDR memory remap/patch facility
eclipse/openj9 pull request #7911
Opened 2019-11-28 21:02 UTC by manqingl

For certain debugging situations, structures may be copied into
malloc'ed memory. It would be nice to be able to use DDR generically in
these cases by allowing the user to remap blocks of memory.

Also when running GCCheck command, the GCCheck command would have to
stop if it encounters a bogus object.  GCCheck command could pass that
bogus object after fixing the memory content.

Signed-off-by: Manqing Li <manqingl@ca.ibm.com>

2019-11-28 21:08 UTC, manqingl commented
@keithc-ca : please review

2019-11-28 22:04 UTC, keithc-ca commented
I'll have a closer look soon, but see my comment in #6888.

2019-11-29 14:25 UTC, manqingl commented
@keithc-ca : I have just fixed the files so all of them are using the Unix style line delimiters.

2019-11-29 14:25 UTC, manqingl commented
I believe the recently added code about BufferedMemory.java and BufferedMemorySource.java would not break the mechanism in this pull request.  The BufferedMemory and BufferedMemorySource added extra logic to the MemorySourceTable.

The new mechanism maintains a separate list of the patched memory. The following sequence describes how we getBytes() with the new mechanism:

Patching or remapping:

(1) DDR command is called to patch the memory.
(2) Add the patched memory into the patched memory list.

Reading memory:
(1) Someone calls AbstractMemory.getBytes() with the start address and size;
(2) If memories at any of those address are patched, get the values from the patched memory list;
(3) If none memories are patched, or if any of the memories are not patched, get the values from the MemorySourceTable 

Clear patched memory:
Remove the patched memory from the list.

2019-11-29 14:33 UTC, manqingl commented
If we choose to modify the MemorySourceTable, we need to search the memory and identify which memory source is patched.

Patching or remapping:
(1) DDR command is called to patch the memory.
(2) Search the memory source table to identify which memory source is to be patched.
(3) Record the memory source in a patched memorySource list, Or record the memory source, addresses, and values and maintain the patch list.

Reading memory:
(1) Someone calls AbstractMemory.getBytes() with the start address and size;
(2) Get the values from the MemorySourceTable

Clear patched memory:
(1) If we record the patched memorySource list, we have to clear all the patched memory source and re-load from the system core file.
(2) If we have the patched memory list, we need to locate the patched memory source, and replace with the original values.  Of course we can choose to get rid of the whole memory sources.

Overall, I believe things can be very complicated because  I assume some memory source in the source table can get "swapped out" unexpectedly. When we have a 10 GB system core file, the memorySourceTable would not be able to contain all the 10 GB.  If we call a !findAll command to search the whole system core file,  the memory source table would only contain a small part of the memory, and thus the memory source table would keep changing or not used.

I believe I would not have time to re-write a mechanism to use MemorySourceTable.  Feel free to take over the issue.

2020-10-13 21:58 UTC, keithc-ca requested changes

2020-10-13 21:58 UTC, keithc-ca commented on debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/memory/MemoryRecord.java
> +		return start + content.length;
I think this should say
```
    return start + length;
```
to avoid an NPE when `content` is `null`.

2020-10-13 21:58 UTC, keithc-ca commented on debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/memory/MemoryRecord.java
> +			out.print(" " + String.format("%02X",  (int) (content[i] & 0xff)));
This can be simplified to
```
    out.format(" %02X",  content[i] & 0xff);
```

2020-10-13 21:58 UTC, keithc-ca commented on debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/memory/PatchedMemoryList.java
> +			} else if (important.getEnd() < list.get(index).getStart()){
Some local variables are in order here, for `important.getStart()`, `important.getEnd()`, `list.size()`, `list.get(index)`, etc.

2020-10-13 21:58 UTC, keithc-ca commented on debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/memory/PatchedMemoryList.java
> +			}
Please put comments before the related code to avoid excessively long lines.

2020-10-13 21:58 UTC, keithc-ca commented on debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/memory/PatchedMemoryList.java
> +	public static boolean verbose = new Boolean(System.getProperty("com.ibm.j9ddr.corereaders.memory.PatchedMemoryList.verbose"));
Suggest:
```
	public static final boolean verbose = Boolean.getBoolean("com.ibm.j9ddr.corereaders.memory.PatchedMemoryList.verbose");
```

2020-10-13 21:58 UTC, keithc-ca commented on debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/tdump/TDumpReader.java
> +					return getBytesAt(address, buffer, 0, buffer.length);
This looks like it will yield infinite recursion, besides ignoring the supplied `offset` and `length` parameters.

2020-10-13 21:58 UTC, keithc-ca commented on debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/tdump/TDumpReader.java
> +			return ByteBuffer.wrap(buffer).getInt();
This should either explicitly set the byte-order of the buffer or include a comment why the default (big-endian) is appropriate.

2020-10-13 21:58 UTC, keithc-ca commented on debugtools/DDR_VM/src/com/ibm/j9ddr/tools/ddrinteractive/commands/PatchMemoryCommand.java
> +		addCommand(COMMAND_VERBOSE, ARGUMENTS_VERBOSE, ARGUMENTS_VERBOSE);
I suggest the set of commands should have a common prefix:
* patch list
* patch set ...
* patch clear ...
...

2020-10-13 21:58 UTC, keithc-ca commented on debugtools/DDR_VM/src/com/ibm/j9ddr/tools/ddrinteractive/commands/PatchMemoryCommand.java
> +		long targetAddress =  new ExpressionEvaluator(args[2]).calculate(16);
These can each be simplified using `ExpressionEvaluator.eval(arg, 16)`.

2020-10-13 21:58 UTC, keithc-ca commented on debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/PatchMemoryCommand.java
> +public class PatchMemoryCommand extends com.ibm.j9ddr.tools.ddrinteractive.commands.PatchMemoryCommand {
I don't see a use of this class.

2020-10-14 09:34 UTC, manqingl commented
@keithc-ca : thanks for your work.  The original purpose of this work is to address a VM issue found in service and I had built a personal build for it.  The original issue has been resolved now.  Therefore this work becomes low priority.  Due to the workload on service, I would not have time to continue this work.  We can close this for now.  We will re-open this pull request and continue this work later if necessary.

2020-10-14 09:34 UTC, closed without merging