WIP: Inlined version of recognized methods
eclipse/openj9 pull request #9841
Opened 2020-06-10 09:01 UTC by sahithiponangi

java_nio_Bits_keepAlive and
 java_lang_ref_Reference_reachabilityFence have been added
 by consulting the semantics on other architectures.

Issue: #7137

Signed-off-by: Siri Sahithi Ponangi <sahithi.ponangi@unb.ca>

2020-06-11 14:58 UTC, 0xdaryl commented on runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
> +            TR::Node *paramNode = node->getFirstChild();
If you copied this implementation from x86, can you copy the comments that were in that code as well?  It helps to explain what this code is trying to achieve.

2020-07-28 04:05 UTC, knn-k commented on runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
> +         case TR::java_lang_ref_Reference_reachabilityFence:
There is a trailing space at the end of this line.

2020-07-29 08:11 UTC, knn-k commented
jenkins test sanity alinux64 jdk11

2021-03-17 20:34 UTC, 0xdaryl commented
jenkins test sanity alinux64 jdk11

Previous checks passed, but re-running in 2021.

2021-03-17 23:49 UTC, knn-k commented
jenkins test sanity alinux64 jdk11

2021-03-18 16:47 UTC, 0xdaryl requested changes
Minor comment about comment content and placement.  Code otherwise is fine.

2021-03-18 16:47 UTC, 0xdaryl commented on runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
> +            TR::Node *paramNode = node->getFirstChild();
I find the placement of these comments to be a bit odd.  Can you move them down below the opening brace like x86 has them?  Also, remove the specific reference to `keepAlive` as this applies to a couple of different recognized methods.  Maybe say "these functions" instead?

2021-03-19 13:33 UTC, 0xdaryl commented
jenkins test sanity alinux64 jdk11

2021-03-19 21:40 UTC, 0xdaryl approved these changes

2021-03-19 21:41 UTC, merged